/**
 * Compliance Report Generator
 * Generates comprehensive compliance reports for all standards
 */

import { ComplianceReport, CheckResult, ComplianceStandard } from './types';

export class ComplianceReportGenerator {
  public generateReport(
    standard: ComplianceStandard,
    results: CheckResult[],
  ): ComplianceReport {
    const passed = results.filter((r) => r.passed).length;
    const failed = results.length - passed;
    const passRate = results.length > 0 ? (passed / results.length) * 100 : 0;

    const overallStatus =
      passRate === 100 ? 'compliant' : passRate >= 80 ? 'partial' : 'non-compliant';

    const recommendations = this.generateRecommendations(results);

    return {
      id: `report-${standard}-${Date.now()}`,
      timestamp: new Date(),
      standard,
      summary: {
        totalChecks: results.length,
        passed,
        failed,
        passRate,
      },
      results,
      overallStatus,
      recommendations,
      nextAuditDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 90 days
    };
  }

  private generateRecommendations(results: CheckResult[]): string[] {
    const recommendations: string[] = [];

    const failedChecks = results.filter((r) => !r.passed);

    // Group by severity
    const criticalFailures = failedChecks.filter((r) => r.checkId.includes('CRITICAL'));
    const highFailures = failedChecks.filter((r) => r.checkId.includes('HIGH'));

    if (criticalFailures.length > 0) {
      recommendations.push(
        `URGENT: Address ${criticalFailures.length} critical compliance failures immediately.`,
      );
    }

    if (highFailures.length > 0) {
      recommendations.push(
        `HIGH PRIORITY: Remediate ${highFailures.length} high-severity issues within 30 days.`,
      );
    }

    // Add specific recommendations
    failedChecks.forEach((check) => {
      if (check.remediation) {
        recommendations.push(check.remediation);
      }
    });

    if (recommendations.length === 0) {
      recommendations.push('Continue monitoring and maintain current compliance state.');
    }

    return recommendations;
  }

  public generateMarkdownReport(report: ComplianceReport): string {
    const markdown = `# ${report.standard} Compliance Report

**Report ID:** ${report.id}
**Generated:** ${report.timestamp.toISOString()}
**Overall Status:** ${report.overallStatus.toUpperCase()}

## Summary

- **Total Checks:** ${report.summary.totalChecks}
- **Passed:** ${report.summary.passed}
- **Failed:** ${report.summary.failed}
- **Pass Rate:** ${report.summary.passRate.toFixed(2)}%

## Results

| Check ID | Check Name | Status | Category | Severity |
|----------|-----------|--------|----------|----------|
${report.results.map((r) => this.formatCheckRow(r)).join('\n')}

## Failed Checks Details

${report.results
  .filter((r) => !r.passed)
  .map((r) => this.formatFailedCheckDetail(r))
  .join('\n\n')}

## Recommendations

${report.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## Next Audit

Next compliance audit scheduled for: ${report.nextAuditDate?.toISOString().split('T')[0]}

---
Generated by Compliance Framework v1.0
`;

    return markdown;
  }

  private formatCheckRow(result: CheckResult): string {
    const status = result.passed ? '✓ Pass' : '✗ Fail';
    const checkId = result.checkId;
    const severity = checkId.includes('CRITICAL') ? 'Critical' : 'High';
    const category = checkId.split('-')[1];

    return `| ${checkId} | ${result.message.substring(0, 30)} | ${status} | ${category} | ${severity} |`;
  }

  private formatFailedCheckDetail(result: CheckResult): string {
    const detail = `### ${result.checkId}

**Message:** ${result.message}

${result.findings ? `**Findings:**\n${result.findings.map((f) => `- ${f}`).join('\n')}\n` : ''}

${result.remediation ? `**Remediation:**\n${result.remediation}\n` : ''}`;

    return detail;
  }

  public generateJsonReport(report: ComplianceReport): string {
    return JSON.stringify(report, null, 2);
  }

  public generateHtmlReport(report: ComplianceReport): string {
    const html = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${report.standard} Compliance Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        h1 { color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }
        .summary-card { background: #f9f9f9; padding: 15px; border-left: 4px solid #007bff; }
        .summary-card h3 { margin: 0; color: #666; font-size: 12px; text-transform: uppercase; }
        .summary-card .value { font-size: 24px; font-weight: bold; color: #333; margin-top: 5px; }
        .status-compliant { color: #28a745; }
        .status-partial { color: #ffc107; }
        .status-non-compliant { color: #dc3545; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #f0f0f0; padding: 12px; text-align: left; border-bottom: 2px solid #ddd; }
        td { padding: 12px; border-bottom: 1px solid #ddd; }
        tr:hover { background: #f9f9f9; }
        .pass { color: #28a745; }
        .fail { color: #dc3545; }
        .check-detail { background: #f9f9f9; padding: 15px; margin: 10px 0; border-left: 4px solid #dc3545; }
        .check-detail.passed { border-left-color: #28a745; }
        .recommendations { background: #fff3cd; padding: 15px; border-radius: 4px; }
        .recommendation-item { margin: 10px 0; padding: 10px; background: white; border-left: 4px solid #ffc107; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <h1>${report.standard} Compliance Report</h1>

        <div style="color: #666; margin-bottom: 20px;">
            <p><strong>Report ID:</strong> ${report.id}</p>
            <p><strong>Generated:</strong> ${report.timestamp.toISOString()}</p>
            <p><strong>Overall Status:</strong> <span class="status-${report.overallStatus}">${report.overallStatus.toUpperCase()}</span></p>
        </div>

        <h2>Summary</h2>
        <div class="summary">
            <div class="summary-card">
                <h3>Total Checks</h3>
                <div class="value">${report.summary.totalChecks}</div>
            </div>
            <div class="summary-card">
                <h3>Passed</h3>
                <div class="value" style="color: #28a745;">${report.summary.passed}</div>
            </div>
            <div class="summary-card">
                <h3>Failed</h3>
                <div class="value" style="color: #dc3545;">${report.summary.failed}</div>
            </div>
            <div class="summary-card">
                <h3>Pass Rate</h3>
                <div class="value">${report.summary.passRate.toFixed(1)}%</div>
            </div>
        </div>

        <h2>Results</h2>
        <table>
            <thead>
                <tr>
                    <th>Check ID</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Category</th>
                </tr>
            </thead>
            <tbody>
                ${report.results.map((r) => `
                <tr>
                    <td>${r.checkId}</td>
                    <td>${r.message}</td>
                    <td class="${r.passed ? 'pass' : 'fail'}">${r.passed ? '✓ Pass' : '✗ Fail'}</td>
                    <td>${r.checkId.split('-')[1]}</td>
                </tr>
                `).join('')}
            </tbody>
        </table>

        <h2>Failed Checks Details</h2>
        ${report.results
          .filter((r) => !r.passed)
          .map((r) => `
            <div class="check-detail">
                <h3>${r.checkId}</h3>
                <p><strong>Message:</strong> ${r.message}</p>
                ${r.findings ? `<p><strong>Findings:</strong><ul>${r.findings.map((f) => `<li>${f}</li>`).join('')}</ul></p>` : ''}
                ${r.remediation ? `<p><strong>Remediation:</strong> ${r.remediation}</p>` : ''}
            </div>
            `).join('')}

        <h2>Recommendations</h2>
        <div class="recommendations">
            ${report.recommendations.map((r) => `<div class="recommendation-item">${r}</div>`).join('')}
        </div>

        <h2>Next Audit</h2>
        <p>Next compliance audit scheduled for: <strong>${report.nextAuditDate?.toISOString().split('T')[0]}</strong></p>

        <div class="footer">
            <p>This report was automatically generated by the Compliance Framework v1.0</p>
            <p>For questions about this report, contact your security team.</p>
        </div>
    </div>
</body>
</html>`;

    return html;
  }

  public generateCsvReport(report: ComplianceReport): string {
    let csv = 'Check ID,Description,Status,Category,Message\n';

    report.results.forEach((r) => {
      const status = r.passed ? 'Pass' : 'Fail';
      const category = r.checkId.split('-')[1];
      const message = r.message.replace(/"/g, '""');
      csv += `"${r.checkId}","${message}","${status}","${category}"\n`;
    });

    return csv;
  }
}
