%% Generated regulation validator for Mortgage Lender (Florida)
%% Regulation: Florida Mortgage Lending Regulations
%% Jurisdiction: Florida
%% Risk Tier: tier_2_regional
%%
%% DO NOT EDIT - Generated by Fortune-5 Regulations Suite Generator
%% This ensures compliance with FL_MORTGAGE_LENDING

-module(f5_reg_mortgage_lender_fl_fl_mortgage_lending_validator).

%% API
-export([validate_all/1, get_regulation_info/0]).
-export([validate_originator_licensing/1, validate_escrow_requirements/1, validate_foreclosure_procedures/1]).

-record(validation_context, {
    customer_id :: binary(),
    jurisdiction :: atom(),
    regulation_id :: atom(),
    data :: map(),
    timestamp :: integer()
}).

%%% API Functions

%% @doc Validate all requirements for this regulation
-spec validate_all(map()) -> {ok, [{atom(), ok}]} | {error, [{atom(), term()}]}.
validate_all(Context) ->
    %% Use function references, not atoms
    Checks = [
        {fun ?MODULE:validate_originator_licensing/1, 'originator_licensing'}, {fun ?MODULE:validate_escrow_requirements/1, 'escrow_requirements'}, {fun ?MODULE:validate_foreclosure_procedures/1, 'foreclosure_procedures'}
    ],

    Results = lists:map(fun({CheckFun, CheckName}) ->
        case CheckFun(Context) of
            {ok, validated} -> {CheckName, ok};
            {error, Reason} -> {CheckName, {error, Reason}}
        end
    end, Checks),

    Failures = [R || {_, {error, _}} = R <- Results],

    case Failures of
        [] -> {ok, Results};
        _ -> {error, Failures}
    end.

%% @doc Get regulation metadata
-spec get_regulation_info() -> map().
get_regulation_info() ->
    #{
        customer_id => "mortgage_lender_fl",
        customer_name => "Mortgage Lender (Florida)",
        jurisdiction => florida,
        regulation_id => fl_mortgage_lending,
        regulation_name => "Florida Mortgage Lending Regulations",
        severity => high,
        risk_tier => tier_2_regional,
        checks => ['originator_licensing', 'escrow_requirements', 'foreclosure_procedures']
    }.


%% @doc Validate originator licensing for Florida Mortgage Lending Regulations
-spec validate_originator_licensing(map()) -> {ok, validated} | {error, term()}.
validate_originator_licensing(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_originator_licensing(Data) of
        true ->
            logger:info("Validation passed: originator_licensing", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: originator_licensing", []),
            {error, {validation_failed, originator_licensing}}
    end.

check_originator_licensing(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(originator_licensing, Data, true);
check_originator_licensing(_) ->
    false.

%% @doc Validate escrow requirements for Florida Mortgage Lending Regulations
-spec validate_escrow_requirements(map()) -> {ok, validated} | {error, term()}.
validate_escrow_requirements(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_escrow_requirements(Data) of
        true ->
            logger:info("Validation passed: escrow_requirements", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: escrow_requirements", []),
            {error, {validation_failed, escrow_requirements}}
    end.

check_escrow_requirements(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(escrow_requirements, Data, true);
check_escrow_requirements(_) ->
    false.

%% @doc Validate foreclosure procedures for Florida Mortgage Lending Regulations
-spec validate_foreclosure_procedures(map()) -> {ok, validated} | {error, term()}.
validate_foreclosure_procedures(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_foreclosure_procedures(Data) of
        true ->
            logger:info("Validation passed: foreclosure_procedures", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: foreclosure_procedures", []),
            {error, {validation_failed, foreclosure_procedures}}
    end.

check_foreclosure_procedures(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(foreclosure_procedures, Data, true);
check_foreclosure_procedures(_) ->
    false.


%%% EUnit Tests

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

get_regulation_info_test() ->
    Info = get_regulation_info(),
    ?assertEqual("mortgage_lender_fl", maps:get(customer_id, Info)),
    ?assertEqual(fl_mortgage_lending, maps:get(regulation_id, Info)).

validate_all_test() ->
    %% All checks pass
    ValidContext = #{
        data => #{originator_licensing => true, escrow_requirements => true, foreclosure_procedures => true}
    },
    {ok, Results} = validate_all(ValidContext),
    ?assertEqual(3, length(Results)),

    %% Some checks fail
    InvalidContext = #{
        data => #{originator_licensing => false}
    },
    {error, Failures} = validate_all(InvalidContext),
    ?assert(length(Failures) > 0).


validate_originator_licensing_test() ->
    ValidContext = #{data => #{originator_licensing => true}},
    ?assertEqual({ok, validated}, validate_originator_licensing(ValidContext)),

    InvalidContext = #{data => #{originator_licensing => false}},
    ?assertMatch({error, _}, validate_originator_licensing(InvalidContext)).

validate_escrow_requirements_test() ->
    ValidContext = #{data => #{escrow_requirements => true}},
    ?assertEqual({ok, validated}, validate_escrow_requirements(ValidContext)),

    InvalidContext = #{data => #{escrow_requirements => false}},
    ?assertMatch({error, _}, validate_escrow_requirements(InvalidContext)).

validate_foreclosure_procedures_test() ->
    ValidContext = #{data => #{foreclosure_procedures => true}},
    ?assertEqual({ok, validated}, validate_foreclosure_procedures(ValidContext)),

    InvalidContext = #{data => #{foreclosure_procedures => false}},
    ?assertMatch({error, _}, validate_foreclosure_procedures(InvalidContext)).


-endif.
