---
# Application RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${NAME}-app-rolebinding
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: gcp-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${NAME}-app-role
subjects:
- kind: ServiceAccount
  name: ${NAME}-app-sa
  namespace: ${NAMESPACE}

---
# Application ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${NAME}-app-cluster-rolebinding
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: gcp-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${NAME}-app-cluster-role
subjects:
- kind: ServiceAccount
  name: ${NAME}-app-sa
  namespace: ${NAMESPACE}

---
# Metering ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${NAME}-metering-rolebinding
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: metering
    app.kubernetes.io/managed-by: gcp-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${NAME}-metering-role
subjects:
- kind: ServiceAccount
  name: ${NAME}-metering-sa
  namespace: ${NAMESPACE}

---
# Admin RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${NAME}-admin-rolebinding
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: admin
    app.kubernetes.io/managed-by: gcp-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${NAME}-admin-role
subjects:
- kind: ServiceAccount
  name: ${NAME}-admin-sa
  namespace: ${NAMESPACE}

---
# Backup RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${NAME}-backup-rolebinding
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: backup
    app.kubernetes.io/managed-by: gcp-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${NAME}-backup-role
subjects:
- kind: ServiceAccount
  name: ${NAME}-backup-sa
  namespace: ${NAMESPACE}
