---
# Application Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}-app-sa
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: service-account
    app.kubernetes.io/managed-by: gcp-marketplace
automountServiceAccountToken: true

---
# Usage Metering Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}-metering-sa
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: metering
    app.kubernetes.io/managed-by: gcp-marketplace
automountServiceAccountToken: true

---
# Admin Service Account (for privileged operations)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}-admin-sa
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: admin
    app.kubernetes.io/managed-by: gcp-marketplace
automountServiceAccountToken: true

---
# Backup Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}-backup-sa
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: backup
    app.kubernetes.io/managed-by: gcp-marketplace
automountServiceAccountToken: true
