{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cre.fullname" . }}
  labels:
    {{- include "cre.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cre.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /status.json
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
