---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cre-pdb
  namespace: cre-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: cre

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cre-pdb
  namespace: cre-staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cre
