PREFIX ln: <http://lnctrl.io/ontology#>
PREFIX f5: <http://fortune5.lnctrl.io/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?appId ?appName ?appDescription
WHERE {
    ?app a ln:Application ;
         ln:appId ?appId ;
         ln:name ?appName .

    OPTIONAL { ?app rdfs:comment ?appDescription }
}
ORDER BY ?appId
