%% Generated regulation validator for Credit Union (Texas)
%% Regulation: Texas Finance Code
%% Jurisdiction: Texas
%% Risk Tier: tier_3_community
%%
%% DO NOT EDIT - Generated by Fortune-5 Regulations Suite Generator
%% This ensures compliance with TX_FINANCE_CODE

-module(f5_reg_credit_union_tx_tx_finance_code_validator).

%% API
-export([validate_all/1, get_regulation_info/0]).
-export([validate_licensing_requirements/1, validate_fee_disclosures/1, validate_complaint_handling/1]).

-record(validation_context, {
    customer_id :: binary(),
    jurisdiction :: atom(),
    regulation_id :: atom(),
    data :: map(),
    timestamp :: integer()
}).

%%% API Functions

%% @doc Validate all requirements for this regulation
-spec validate_all(map()) -> {ok, [{atom(), ok}]} | {error, [{atom(), term()}]}.
validate_all(Context) ->
    %% Use function references, not atoms
    Checks = [
        {fun ?MODULE:validate_licensing_requirements/1, 'licensing_requirements'}, {fun ?MODULE:validate_fee_disclosures/1, 'fee_disclosures'}, {fun ?MODULE:validate_complaint_handling/1, 'complaint_handling'}
    ],

    Results = lists:map(fun({CheckFun, CheckName}) ->
        case CheckFun(Context) of
            {ok, validated} -> {CheckName, ok};
            {error, Reason} -> {CheckName, {error, Reason}}
        end
    end, Checks),

    Failures = [R || {_, {error, _}} = R <- Results],

    case Failures of
        [] -> {ok, Results};
        _ -> {error, Failures}
    end.

%% @doc Get regulation metadata
-spec get_regulation_info() -> map().
get_regulation_info() ->
    #{
        customer_id => "credit_union_tx",
        customer_name => "Credit Union (Texas)",
        jurisdiction => texas,
        regulation_id => tx_finance_code,
        regulation_name => "Texas Finance Code",
        severity => high,
        risk_tier => tier_3_community,
        checks => ['licensing_requirements', 'fee_disclosures', 'complaint_handling']
    }.


%% @doc Validate licensing requirements for Texas Finance Code
-spec validate_licensing_requirements(map()) -> {ok, validated} | {error, term()}.
validate_licensing_requirements(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_licensing_requirements(Data) of
        true ->
            logger:info("Validation passed: licensing_requirements", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: licensing_requirements", []),
            {error, {validation_failed, licensing_requirements}}
    end.

check_licensing_requirements(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(licensing_requirements, Data, true);
check_licensing_requirements(_) ->
    false.

%% @doc Validate fee disclosures for Texas Finance Code
-spec validate_fee_disclosures(map()) -> {ok, validated} | {error, term()}.
validate_fee_disclosures(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_fee_disclosures(Data) of
        true ->
            logger:info("Validation passed: fee_disclosures", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: fee_disclosures", []),
            {error, {validation_failed, fee_disclosures}}
    end.

check_fee_disclosures(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(fee_disclosures, Data, true);
check_fee_disclosures(_) ->
    false.

%% @doc Validate complaint handling for Texas Finance Code
-spec validate_complaint_handling(map()) -> {ok, validated} | {error, term()}.
validate_complaint_handling(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_complaint_handling(Data) of
        true ->
            logger:info("Validation passed: complaint_handling", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: complaint_handling", []),
            {error, {validation_failed, complaint_handling}}
    end.

check_complaint_handling(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(complaint_handling, Data, true);
check_complaint_handling(_) ->
    false.


%%% EUnit Tests

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

get_regulation_info_test() ->
    Info = get_regulation_info(),
    ?assertEqual("credit_union_tx", maps:get(customer_id, Info)),
    ?assertEqual(tx_finance_code, maps:get(regulation_id, Info)).

validate_all_test() ->
    %% All checks pass
    ValidContext = #{
        data => #{licensing_requirements => true, fee_disclosures => true, complaint_handling => true}
    },
    {ok, Results} = validate_all(ValidContext),
    ?assertEqual(3, length(Results)),

    %% Some checks fail
    InvalidContext = #{
        data => #{licensing_requirements => false}
    },
    {error, Failures} = validate_all(InvalidContext),
    ?assert(length(Failures) > 0).


validate_licensing_requirements_test() ->
    ValidContext = #{data => #{licensing_requirements => true}},
    ?assertEqual({ok, validated}, validate_licensing_requirements(ValidContext)),

    InvalidContext = #{data => #{licensing_requirements => false}},
    ?assertMatch({error, _}, validate_licensing_requirements(InvalidContext)).

validate_fee_disclosures_test() ->
    ValidContext = #{data => #{fee_disclosures => true}},
    ?assertEqual({ok, validated}, validate_fee_disclosures(ValidContext)),

    InvalidContext = #{data => #{fee_disclosures => false}},
    ?assertMatch({error, _}, validate_fee_disclosures(InvalidContext)).

validate_complaint_handling_test() ->
    ValidContext = #{data => #{complaint_handling => true}},
    ?assertEqual({ok, validated}, validate_complaint_handling(ValidContext)),

    InvalidContext = #{data => #{complaint_handling => false}},
    ?assertMatch({error, _}, validate_complaint_handling(InvalidContext)).


-endif.
