%% Generated regulation validator for Credit Union (Texas)
%% Regulation: NCUA Part 701 (Credit Union Regulations)
%% Jurisdiction: Texas
%% Risk Tier: tier_3_community
%%
%% DO NOT EDIT - Generated by Fortune-5 Regulations Suite Generator
%% This ensures compliance with NCUA_PART_701

-module(f5_reg_credit_union_tx_ncua_part_701_validator).

%% API
-export([validate_all/1, get_regulation_info/0]).
-export([validate_member_rights/1, validate_loan_limits/1, validate_investment_restrictions/1]).

-record(validation_context, {
    customer_id :: binary(),
    jurisdiction :: atom(),
    regulation_id :: atom(),
    data :: map(),
    timestamp :: integer()
}).

%%% API Functions

%% @doc Validate all requirements for this regulation
-spec validate_all(map()) -> {ok, [{atom(), ok}]} | {error, [{atom(), term()}]}.
validate_all(Context) ->
    %% Use function references, not atoms
    Checks = [
        {fun ?MODULE:validate_member_rights/1, 'member_rights'}, {fun ?MODULE:validate_loan_limits/1, 'loan_limits'}, {fun ?MODULE:validate_investment_restrictions/1, 'investment_restrictions'}
    ],

    Results = lists:map(fun({CheckFun, CheckName}) ->
        case CheckFun(Context) of
            {ok, validated} -> {CheckName, ok};
            {error, Reason} -> {CheckName, {error, Reason}}
        end
    end, Checks),

    Failures = [R || {_, {error, _}} = R <- Results],

    case Failures of
        [] -> {ok, Results};
        _ -> {error, Failures}
    end.

%% @doc Get regulation metadata
-spec get_regulation_info() -> map().
get_regulation_info() ->
    #{
        customer_id => "credit_union_tx",
        customer_name => "Credit Union (Texas)",
        jurisdiction => texas,
        regulation_id => ncua_part_701,
        regulation_name => "NCUA Part 701 (Credit Union Regulations)",
        severity => high,
        risk_tier => tier_3_community,
        checks => ['member_rights', 'loan_limits', 'investment_restrictions']
    }.


%% @doc Validate member rights for NCUA Part 701 (Credit Union Regulations)
-spec validate_member_rights(map()) -> {ok, validated} | {error, term()}.
validate_member_rights(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_member_rights(Data) of
        true ->
            logger:info("Validation passed: member_rights", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: member_rights", []),
            {error, {validation_failed, member_rights}}
    end.

check_member_rights(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(member_rights, Data, true);
check_member_rights(_) ->
    false.

%% @doc Validate loan limits for NCUA Part 701 (Credit Union Regulations)
-spec validate_loan_limits(map()) -> {ok, validated} | {error, term()}.
validate_loan_limits(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_loan_limits(Data) of
        true ->
            logger:info("Validation passed: loan_limits", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: loan_limits", []),
            {error, {validation_failed, loan_limits}}
    end.

check_loan_limits(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(loan_limits, Data, true);
check_loan_limits(_) ->
    false.

%% @doc Validate investment restrictions for NCUA Part 701 (Credit Union Regulations)
-spec validate_investment_restrictions(map()) -> {ok, validated} | {error, term()}.
validate_investment_restrictions(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_investment_restrictions(Data) of
        true ->
            logger:info("Validation passed: investment_restrictions", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: investment_restrictions", []),
            {error, {validation_failed, investment_restrictions}}
    end.

check_investment_restrictions(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(investment_restrictions, Data, true);
check_investment_restrictions(_) ->
    false.


%%% EUnit Tests

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

get_regulation_info_test() ->
    Info = get_regulation_info(),
    ?assertEqual("credit_union_tx", maps:get(customer_id, Info)),
    ?assertEqual(ncua_part_701, maps:get(regulation_id, Info)).

validate_all_test() ->
    %% All checks pass
    ValidContext = #{
        data => #{member_rights => true, loan_limits => true, investment_restrictions => true}
    },
    {ok, Results} = validate_all(ValidContext),
    ?assertEqual(3, length(Results)),

    %% Some checks fail
    InvalidContext = #{
        data => #{member_rights => false}
    },
    {error, Failures} = validate_all(InvalidContext),
    ?assert(length(Failures) > 0).


validate_member_rights_test() ->
    ValidContext = #{data => #{member_rights => true}},
    ?assertEqual({ok, validated}, validate_member_rights(ValidContext)),

    InvalidContext = #{data => #{member_rights => false}},
    ?assertMatch({error, _}, validate_member_rights(InvalidContext)).

validate_loan_limits_test() ->
    ValidContext = #{data => #{loan_limits => true}},
    ?assertEqual({ok, validated}, validate_loan_limits(ValidContext)),

    InvalidContext = #{data => #{loan_limits => false}},
    ?assertMatch({error, _}, validate_loan_limits(InvalidContext)).

validate_investment_restrictions_test() ->
    ValidContext = #{data => #{investment_restrictions => true}},
    ?assertEqual({ok, validated}, validate_investment_restrictions(ValidContext)),

    InvalidContext = #{data => #{investment_restrictions => false}},
    ?assertMatch({error, _}, validate_investment_restrictions(InvalidContext)).


-endif.
