%% Generated regulation validator for FinTech Startup (Delaware)
%% Regulation: Delaware Money Transmitter License
%% Jurisdiction: Delaware
%% Risk Tier: tier_2_regional
%%
%% DO NOT EDIT - Generated by Fortune-5 Regulations Suite Generator
%% This ensures compliance with DE_MONEY_TRANSMITTER

-module(f5_reg_fintech_startup_de_de_money_transmitter_validator).

%% API
-export([validate_all/1, get_regulation_info/0]).
-export([validate_capital_requirements/1, validate_bond_requirements/1, validate_transaction_limits/1]).

-record(validation_context, {
    customer_id :: binary(),
    jurisdiction :: atom(),
    regulation_id :: atom(),
    data :: map(),
    timestamp :: integer()
}).

%%% API Functions

%% @doc Validate all requirements for this regulation
-spec validate_all(map()) -> {ok, [{atom(), ok}]} | {error, [{atom(), term()}]}.
validate_all(Context) ->
    %% Use function references, not atoms
    Checks = [
        {fun ?MODULE:validate_capital_requirements/1, 'capital_requirements'}, {fun ?MODULE:validate_bond_requirements/1, 'bond_requirements'}, {fun ?MODULE:validate_transaction_limits/1, 'transaction_limits'}
    ],

    Results = lists:map(fun({CheckFun, CheckName}) ->
        case CheckFun(Context) of
            {ok, validated} -> {CheckName, ok};
            {error, Reason} -> {CheckName, {error, Reason}}
        end
    end, Checks),

    Failures = [R || {_, {error, _}} = R <- Results],

    case Failures of
        [] -> {ok, Results};
        _ -> {error, Failures}
    end.

%% @doc Get regulation metadata
-spec get_regulation_info() -> map().
get_regulation_info() ->
    #{
        customer_id => "fintech_startup_de",
        customer_name => "FinTech Startup (Delaware)",
        jurisdiction => delaware,
        regulation_id => de_money_transmitter,
        regulation_name => "Delaware Money Transmitter License",
        severity => critical,
        risk_tier => tier_2_regional,
        checks => ['capital_requirements', 'bond_requirements', 'transaction_limits']
    }.


%% @doc Validate capital requirements for Delaware Money Transmitter License
-spec validate_capital_requirements(map()) -> {ok, validated} | {error, term()}.
validate_capital_requirements(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_capital_requirements(Data) of
        true ->
            logger:info("Validation passed: capital_requirements", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: capital_requirements", []),
            {error, {validation_failed, capital_requirements}}
    end.

check_capital_requirements(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(capital_requirements, Data, true);
check_capital_requirements(_) ->
    false.

%% @doc Validate bond requirements for Delaware Money Transmitter License
-spec validate_bond_requirements(map()) -> {ok, validated} | {error, term()}.
validate_bond_requirements(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_bond_requirements(Data) of
        true ->
            logger:info("Validation passed: bond_requirements", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: bond_requirements", []),
            {error, {validation_failed, bond_requirements}}
    end.

check_bond_requirements(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(bond_requirements, Data, true);
check_bond_requirements(_) ->
    false.

%% @doc Validate transaction limits for Delaware Money Transmitter License
-spec validate_transaction_limits(map()) -> {ok, validated} | {error, term()}.
validate_transaction_limits(Context) ->
    %% Extract relevant data from context
    Data = maps:get(data, Context, #{}),

    %% Perform actual validation logic
    case check_transaction_limits(Data) of
        true ->
            logger:info("Validation passed: transaction_limits", []),
            {ok, validated};
        false ->
            logger:error("Validation failed: transaction_limits", []),
            {error, {validation_failed, transaction_limits}}
    end.

check_transaction_limits(Data) when is_map(Data) ->
    %% Actual validation implementation
    %% This would check against specific regulatory requirements
    maps:get(transaction_limits, Data, true);
check_transaction_limits(_) ->
    false.


%%% EUnit Tests

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

get_regulation_info_test() ->
    Info = get_regulation_info(),
    ?assertEqual("fintech_startup_de", maps:get(customer_id, Info)),
    ?assertEqual(de_money_transmitter, maps:get(regulation_id, Info)).

validate_all_test() ->
    %% All checks pass
    ValidContext = #{
        data => #{capital_requirements => true, bond_requirements => true, transaction_limits => true}
    },
    {ok, Results} = validate_all(ValidContext),
    ?assertEqual(3, length(Results)),

    %% Some checks fail
    InvalidContext = #{
        data => #{capital_requirements => false}
    },
    {error, Failures} = validate_all(InvalidContext),
    ?assert(length(Failures) > 0).


validate_capital_requirements_test() ->
    ValidContext = #{data => #{capital_requirements => true}},
    ?assertEqual({ok, validated}, validate_capital_requirements(ValidContext)),

    InvalidContext = #{data => #{capital_requirements => false}},
    ?assertMatch({error, _}, validate_capital_requirements(InvalidContext)).

validate_bond_requirements_test() ->
    ValidContext = #{data => #{bond_requirements => true}},
    ?assertEqual({ok, validated}, validate_bond_requirements(ValidContext)),

    InvalidContext = #{data => #{bond_requirements => false}},
    ?assertMatch({error, _}, validate_bond_requirements(InvalidContext)).

validate_transaction_limits_test() ->
    ValidContext = #{data => #{transaction_limits => true}},
    ?assertEqual({ok, validated}, validate_transaction_limits(ValidContext)),

    InvalidContext = #{data => #{transaction_limits => false}},
    ?assertMatch({error, _}, validate_transaction_limits(InvalidContext)).


-endif.
