# Generated by SessionStart.sh - source for OTP 28+ environment
export PATH="/usr/bin:/bin:/usr/local/bin:/Users/sac/cre/.erlmcp/otp-28.3.1/bin:$PATH"
export CLAUDE_CODE_REMOTE=true
export ERLMCP_PROFILE=cloud
export ERLMCP_CACHE="/Users/sac/cre/.erlmcp/cache/"
export TERM=dumb
export REBAR_COLOR=none
export ERL_AFLAGS="-kernel shell_history enabled"
